# Consider [Example 11.4](../11.1-intro-to-markov-chains/summary-of-chapter.ipynb#Examples) with $a=0.5$ and $b=0.75$

# Assume the President says that he or she will run

# Find the expected length of time before the answer is passed on incorrectly

_____

# $P=\begin{pmatrix}0.5 & 0.5\\ 0.75 & 0.25\end{pmatrix}$

# $wP = w \implies 0.5w_{1}+0.75w_{2} = w_{1} \implies w_{1} = (3/2)w_{2}$

# $w_{1}+w_{2} = 1 \implies (5/2)w_{2} = 1 \implies w_{2} = (2/5) \implies w_{1} = 3/5$

# $\implies w = [2/5,3/5] \implies W = \begin{pmatrix}3/5 & 2/5\\ 3/5 & 2/5\end{pmatrix}$

In [1]:
import numpy as np

In [16]:
I = np.identity(2)
P = np.array([[0.5, 0.5],[0.75, 0.25]])
W = np.array([[3/5.0,2/5.0],[3/5.0,2/5.0]])

In [17]:
matrix = I - P + W
matrix

array([[ 1.1 , -0.1 ],
       [-0.15,  1.15]])

# $\implies I - P + W = \begin{pmatrix}1.1 & -0.1\\ -0.15 & 1.15\end{pmatrix}$

In [18]:
Z = np.linalg.inv(matrix)
Z

array([[ 0.92,  0.08],
       [ 0.12,  0.88]])

# $\implies Z = \begin{pmatrix}0.92 & 0.08\\ 0.12 & 0.88\end{pmatrix}$

In [19]:
def calc_M(Z, W):
    Z_diagonals = np.repeat(np.diag(Z)[:,np.newaxis], len(Z), axis = 1).T
    return (Z_diagonals-Z)/W

In [20]:
M = calc_M(Z, W)

In [21]:
M

array([[ 0.        ,  2.        ],
       [ 1.33333333,  0.        ]])

# $\implies M = \begin{pmatrix}0 & 2\\ 4/3 & 0\end{pmatrix}$

# Therefore, we expect it will take 2 steps

_____

### Let's confirm this with a simulation

In [9]:
def step(x):
    rand = np.random.random()
    if x == 'Y':
        if rand < 0.5:
            return 'N'
        else:
            return 'Y'
    else:
        if rand < 0.25:
            return 'N'
        else:
            return 'Y'

In [10]:
def count_steps():
    x = 'Y'
    i = 0
    while x != 'N':
        i += 1
        x = step(x)
    return i

In [14]:
list_results = []

for i in range(100000):
    list_results.append(count_steps())

In [15]:
np.mean(list_results)

2.00136

**Bang on**