# In this section, we consider two quantities for erdogic chains:

## 1. Mean time to return to a state

## 2. Mean time to go from state $s_{i}$ to $s_{j}$

# If $w$ is the unique fixed probability vector for an erdogic chain $P$, we know by the Law of Large numbers that we can expect the process to spend a proportion $w_{i}$ of steps in state $s_{i}$

# If $s_{i}$ is the only absorbing state in the chain, we know with probability 1 that the process will eventually end up in state $s_{i}$

# Let $N$ be the fundamental matrix for $P$

# We know that element $n_{ij}$ tells us the expected number of steps spent in state $s_{j}$ given that we start in state $s_{i}$

# We also know that $Nc$ gives us the expected number of steps between starting in each state and being absorbed

_____

# Definition - *Mean First Passage Time*

### If an ergogic Markov chain starts in state $s_{i}$, the expected number of steps to reach state $s_{j}$ for the first time is called the *mean passage time from $s_{i}$ to $s_{j}$

### It is denoted $m_{ij}$

### Note: by convention, $m_{ii} = 0$

____

## Example

### Consider the transition matrix from the maze problem

## $P = \begin{pmatrix}0 & 0.5 & 0 & 0 & 0.5 & 0 & 0 & 0 & 0\\ 0.3333 & 0 & 0.3333 & 0 & 0 & 0 & 0 & 0 & 0.3333\\ 
0 & 0.5 & 0 & 0.5 & 0 & 0 & 0 & 0 & 0\\ 0 & 0 & 0.3333 & 0 & 0 & 0.3333 & 0 & 0.3333 & 0.3333\\ 0.3333 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.3333\\ 0 & 0 & 0 & 0 & 0.5 & 0 & 0.5 & 0 & 0\\ 0 & 0 & 0 & 0 & 0 & 0.3333 & 0 & 0.3333 & 0.3333\\ 0 & 0 & 0 & 0.5 & 0 & 0 & 0.5 & 0 & 0\\ 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\end{pmatrix}$

## $\implies Q = \begin{pmatrix}0 & 0.5 & 0 & 0 & 0.5 & 0 & 0 & 0\\ 0.3333 & 0 & 0.3333 & 0 & 0 & 0 & 0 & 0\\ 
0 & 0.5 & 0 & 0.5 & 0 & 0 & 0 & 0\\ 0 & 0 & 0.3333 & 0 & 0 & 0.3333 & 0 & 0.3333\\ 0.3333 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\ 0 & 0 & 0 & 0 & 0.5 & 0 & 0.5 & 0\\ 0 & 0 & 0 & 0 & 0 & 0.3333 & 0 & 0.3333\\ 0 & 0 & 0 & 0.5 & 0 & 0 & 0.5 & 0\end{pmatrix}$

## $\implies (I-Q) = \begin{pmatrix}1 & -0.5 & 0 & 0 & -0.5 & 0 & 0 & 0\\ -0.3333 & 1 & -0.3333 & 0 & 0 & 0 & 0 & 0\\ 
0 & -0.5 & 1 & -0.5 & 0 & 0 & 0 & 0\\ 0 & 0 & -0.3333 & 1 & 0 & -0.3333 & 0 & -0.3333\\ -0.3333 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\ 0 & 0 & 0 & 0 & -0.5 & 1 & -0.5 & 0\\ 0 & 0 & 0 & 0 & 0 & -0.3333 & 1 & -0.3333\\ 0 & 0 & 0 & -0.5 & 0 & 0 & -0.5 & 1\end{pmatrix}$

**Using numpy to calculate the inverse**

In [1]:
import numpy as np

In [4]:
matrix = np.array([[1 , -0.5 , 0 , 0 , -0.5 , 0 , 0 , 0],
                   [ -1/3.0 , 1 , -1/3.0 , 0 , 0 , 0 , 0 , 0],
                   [ 0 , -0.5 , 1 , -0.5 , 0 , 0 , 0 , 0],
                   [ 0 , 0 , -1/3.0 , 1 , 0 , -1/3.0 , 0 , -1/3.0],
                   [ -1/3.0 , 0 , 0 , 0 , 1 , 0 , 0 , 0],
                   [ 0 , 0 , 0 , 0 , -0.5 , 1 , -0.5 , 0],
                   [ 0 , 0 , 0 , 0 , 0 , -1/3.0 , 1 , -1/3.0],
                   [ 0 , 0 , 0 , -0.5 , 0 , 0 , -0.5 , 1]])

In [6]:
N = np.linalg.inv(matrix)

In [19]:
c = np.array([[1],[1],[1],[1],[1],[1],[1],[1]])

In [20]:
Nc = np.matmul(N,c)

In [21]:
Nc

array([[ 4.8],
       [ 5. ],
       [ 7.2],
       [ 7.4],
       [ 2.6],
       [ 4.8],
       [ 5. ],
       [ 7.2]])

______

# Definition - *Mean Recurrence Time*

### Recall: If a chain is erdogic, it cannot have any absorbing states

## Then, we know that after enough steps, for any pair of states $s_{i}$ and $s_{j}$, there is a non-zero probability that the process will transition from state $s_{i}$ to $s_{j}$

## From this, we can extrapolate the idea that there is a non-zero probability that $s_{i}$ will transition to state $s_{j}$, then back to state $s_{i}$

## The *Mean Recurrence Time* for $s_{i}$ tells us the expected number of steps it'll take for the process to transition away from $s_{i}$, then back to $s_{i}$

## The mean recurrence time for $s_{i}$ is denoted $r_{i}$

## (1) $m_{ij} = 1 + \sum_{k\neq j} p_{ik}m_{kj}$

## (2) $r_{i} = 1 + \sum_{k}p_{ik}m_{ki}$

_____

# Mean First Passage Matrix & Mean Recurrence Matrix

## Let $M$ be the *mean first passage matrix*

## The element $m_{ij}$ represents the mean passage time from $s_{i}$ to $s_{j}$

### Recall: $m_{ii}=0$  by definition $\implies$ the diagonals of $M$ are all zero

## Let $D$ be the *mean recurrence matrix*

## $D$ has all zero values, except on the diagonal where $d_{ii} = r_{i}$ i.e. the mean recurrence time for state $s_{i}$

## Let $C$ be the matrix of all 1s

# $M = PM + C - D \implies (I-P)M = C-D$

____

# Theorem 11.15

### For an erdogic Markov chain, the mean recurrence time for state $s_{i}$ is $r_{i} = \frac{1}{w_{i}}$

_____

## Example

### For a fixed probability vector $w = [1/12, 1/8, 1/12, 1/8, 1/6, 1/8, 1/12, 1/8, 1/12]$ 

### We calculate the mean recurrence times as $r = [12, 8, 12, 8, 6, 8, 12, 8, 12]$

### This implies that to when the process leaves $s_{1}$, it will take around 12 steps before the process returns

_____

## Example

### In the Land of Oz example, we found that $w = [2/5, 1/5, 2/5]$

### This means that we expect there to be 2.5 days between rainy days, 2.5 days between snowy days, and 5 days between nice days

____

# *Fundamental Matrix*

### For *absorbing* chains, we calculate the fundamental matrix $N = (I-Q)^{-1}$

### We want to find an equivalent matrix for *erdogic* chains

___

# Proposition 11.1

### Let $P$ be the transition matrix of an erdogic chain, and let $W$ be the matrix of fixed probability vectors i.e. $W = \begin{bmatrix}w\\ w\\ w\\ w\end{bmatrix} = \begin{bmatrix}w_{1} & w_{2} & ... & w_{n}\\ w_{1} & w_{2} & ... & w_{n}\\  &  & ... & \\ w_{1} & w_{2} & ... & w_{n}\end{bmatrix}$ where $wP = w$

## Then, the matrix $I-P+W$ has an inverse $Z$

 _____
 
 # *Using $Z$ to Calculate the Mean First Passage Matrix $M$*
 
 # Lemma 11.2
 
 ### Let $Z=(I-P+W)^{-1}$ and let $z$ be the column vector of 1s
 
 ### Then
 
 # (1) $Zc = c$
 
 # (2) $wZ = w$
 
 # (3) $Z(I-P) = I-W$

# Theorem 11.16

### The mean first passage matrix $M$ for an erdogic chain is determined from the fundamental matrix $Z$ and the fixed row probability vector $w$ by

# $m_{ij} = \frac{z_{jj}-z_{ij}}{w_{j}}$

______

## Example

### The matrix $P$ from the Land of Oz example was:

# $P = \begin{pmatrix}0.5 & 0.25 & 0.25\\ 0.5 & 0 & 0.5\\ 0.25 & 0.25 & 0.5\end{pmatrix}$

# We also found that $w = [2/5, 1/5, 2/5]$

# $\implies W = \begin{pmatrix}0.4 & 0.2 & 0.4\\0.4 & 0.2 & 0.4\\0.4 & 0.2 & 0.4\end{pmatrix}$

### $\implies (I - P + W) = \begin{pmatrix}1 & 0 & 0\\ 0 & 1 & 0\\ 0 & 0 & 1\end{pmatrix} - \begin{pmatrix}0.5 & 0.25 & 0.25\\ 0.5 & 0 & 0.5\\ 0.25 & 0.5 & 0.25\end{pmatrix} + \begin{pmatrix}0.4 & 0.2 & 0.4\\0.4 & 0.2 & 0.4\\0.4 & 0.2 & 0.4\end{pmatrix}$

### $ = \begin{pmatrix}0.9 & -0.05 & 0.15\\ -0.1 & 1.2 & -0.1\\ 0.15 & -0.05 & 0.9\end{pmatrix}$

**Using numpy to solve for the inverse**

In [22]:
import numpy as np

In [59]:
I = np.identity(3)
P = np.array([[0.5, 0.25, 0.25],[0.5,0,0.5],[0.25,0.25,0.5]])
W = np.repeat([[0.4],[0.2],[0.4]],3, axis = 1).T

In [60]:
W

array([[ 0.4,  0.2,  0.4],
       [ 0.4,  0.2,  0.4],
       [ 0.4,  0.2,  0.4]])

In [61]:
I - P + W

array([[ 0.9 , -0.05,  0.15],
       [-0.1 ,  1.2 , -0.1 ],
       [ 0.15, -0.05,  0.9 ]])

In [62]:
Z = np.linalg.inv(I - P + W)
Z

array([[ 1.14666667,  0.04      , -0.18666667],
       [ 0.08      ,  0.84      ,  0.08      ],
       [-0.18666667,  0.04      ,  1.14666667]])

# $\implies Z = \begin{pmatrix}1.13684211 & 0.01052632 & 0.14736842\\0.08421053 & 0.85263158 & 0.06315789\\-0.12631579 & 0.22105263 & 0.90526316\end{pmatrix}$

In [63]:
def calc_val(Z, W):
    Z_diagonals = np.repeat(np.diag(Z)[:,np.newaxis], len(Z), axis = 1).T
    return (Z_diagonals-Z)/W

In [66]:
M = calc_val(Z, W)
M

array([[ 0.        ,  4.        ,  3.33333333],
       [ 2.66666667,  0.        ,  2.66666667],
       [ 3.33333333,  4.        ,  0.        ]])

# $\implies M = \begin{pmatrix}0 & 4 & 3.33333333\\2.66666667 & 0 & 2.66666667\\3.33333333 & 4 & 0\end{pmatrix}$